### ISSUE TITLE
The source IQueryable doesn't implement IDbAsyncEnumerable

### ISSUE THREAD

**Issue by jenscski** [scottksmith95/LINQKit#39]
After updating from 1.1.3.1 to 1.1.7, the following error appeared

The source IQueryable doesn't implement IDbAsyncEnumerable<T>. Only sources that implement IDbAsyncEnumerable can be used for Entity Framework asynchronous operations.

The NuGet is used in a class library targeting .Net Plaform 4.5.

What I think I have found out is that the ExpandableQuery does not implement IDbAsyncEnumerable<T>.

I have tried to look at the source code, but the .Net Core thing is something I haven't had time to look into yet.

**Comment by jenscski** [comment]
I found out what to do.

Install https://www.nuget.org/packages/LinqKit.EntityFramework/ instead.

For your information, the links in the README does not work (click on the images), that's why I thought I should be using the LinqKit, and not a EntityFramework specific version.

**Comment by StefH** [comment]
Thanks.

I have updated the links in the readme
